documents/urls.py
from django.urls import path
from . import views

app_name = 'documents'

urlpatterns = [
    path('', views.document_list, name='document_list'),
    path('upload/', views.upload_document, name='upload_document'),
    path('downloads/', views.download_view, name='downloads'),
    path('downloads/subcategory/<int:pk>/', views.download_subcategory_detail, name='download_subcategory_detail'),

    # Use primary key instead of slug
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
    path('subcategory/<int:pk>/', views.subcategory_detail, name='subcategory_detail'),

    path('get-subcategories/', views.get_subcategories, name='get_subcategories'),

    # Document views now use pk
    path('document/<int:pk>/', views.document_detail, name='document_detail'),
    path('document/<int:pk>/download/', views.download_document, name='download_document'),
    path('document/<int:pk>/view/', views.view_document, name='view_document'),
    path('document/<int:pk>/edit/', views.update_document, name='update_document'),
    path('document/<int:pk>/delete/', views.delete_document, name='delete_document'),
    path('preview/<int:pk>/', views.embedded_preview, name='embedded_preview'),
    
]

home/urls.py
from django.urls import path
from . import views
from .views import login_view
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_view, name='about'),
    path('students/', views.students_view, name='students'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    
]

 

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  # Import static
from django.contrib.auth import views as auth_views
from dashboard import views as dashboard_views


urlpatterns = [
    path('katubalevu/', admin.site.urls),
    path('', include('home.urls')),
    path('news/', include('news.urls')),
    path('documents/', include(('documents.urls', 'documents'), namespace='documents')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('tinymce/', include('tinymce.urls')),
    path('events/', include('events.urls')),
    path('dashboard/', include('dashboard.urls')),


   
]

# Serve media files only in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('create/', views.create_news, name='create_news'),
    path('<slug:slug>/edit/', views.update_news, name='update_news'),
    path('<slug:slug>/delete/', views.delete_news, name='delete_news'),
    path('<slug:slug>/', views.news_detail, name='news_detail'),
    path('category/<slug:slug>/', views.category_view, name='category_view')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Kalabu Primary School | Ni sa bula vinaka</title>
  <meta name="description" content="The official website for Kalabu Primary School in the Fiji Islands">
  <meta name="keywords" content="Kalabu, Fiji Primary School, KPS,">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
  
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css ' %}" rel="stylesheet">

</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="{% static 'assets/img/logo.png' %}" alt="School Logo" style="width: 50px; height: auto;">
         <i class="bi bi-buildings"></i> -->
        <h1 class="sitename">Kalabu Primary School</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li>
            <a href="{% url 'home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a>
          </li>
          <li>
            <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">About Us</a>
          </li>
          <li>
            <a href="{% url 'students' %}" class="{% if request.resolver_match.url_name == 'students' %}active{% endif %}">Student Life</a>
          </li>
          <li>
            <a href="{% url 'news:news_list' %}" class="{% if request.resolver_match.namespace == 'news' %}active{% endif %}">News</a>
          </li>
          <li>
            <a href="{% url 'documents:downloads' %}" class="{% if request.resolver_match.namespace == 'documents' %}active{% endif %}">Downloads</a>
          </li>
      
          {% if user.is_authenticated %}

          <li>
            <a href="{% url 'documents:document_list' %}" class="{% if request.resolver_match.namespace == 'documents_list' %}active{% endif %}">Documents</a>
          </li>
            
            <li class="nav-item">
              <form action="{% url 'logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="nav-link" style="
                  background: none;
                  border: none;
                  display: block;
                  padding: 0.5rem 1rem;
                  color: rgba(43, 195, 206, 0.55);
                  text-decoration: none;
                  transition: color 0.15s ease-in-out;
                ">
                  Logout
                </button>
              </form>
            </li>
            
          {% else %}
            <li>
              <a href="{% url 'login' %}" class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}">Login</a>
            </li>
          {% endif %}
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>    
      
    </div>
  </header>

  <main class="main">
    {% block content %}
    {% endblock %}
  </main>

  <footer id="footer" class="footer position-relative dark-background">

  <div class="container footer-top">
    <div class="row gy-4">
      <!-- Contact Us -->
      <div class="col-lg-4 col-md-6 footer-about">
        <a href="index.html" class="logo d-flex align-items-center">
          <span class="sitename">Contact Us</span>
        </a>
        <div class="footer-contact pt-3">
          <p>Kalabu</p>
          <p>Kubukawa Road</p>
          <p class="mt-3"><strong>Phone:</strong> <span>+679 3392 699</span></p>
          <p class="mt-3"><strong>Mobile:</strong> <span>+679 865 7899</span></p>
          <p><strong>Email:</strong> <span>kalabuprimaryschool@yahoo.com</span></p>
        </div>
        <div class="social-links d-flex mt-4">
          <a href="https://www.facebook.com/groups/478517484956578" target="blank">
            <i class="bi bi-facebook facebook-blue"></i>
          </a>
        </div>
      </div>
      <!-- My Links -->
      <div class="col-lg-4 col-md-6 footer-links">
        <h4>My Links</h4>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'about' %}">About us</a></li>
          <li><a href="{% url 'students' %}">Students Life</a></li>
          <li><a href="{% url 'news:news_list' %}">News</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
        </ul>
      </div>

      <!-- Other Links -->
      <div class="col-lg-4 col-md-6 footer-links">
        <h4>Other Links</h4>
        <ul>
          <li><a href="https://www.education.gov.fj/">Ministry of Education</a></li>
          <li><a href="http://www.femis.gov.fj/">FEMIS</a></li>
          <li><a href="https://www.usp.ac.fj/">USP</a></li>
          <li><a href="https://www.fnu.ac.fj/">FNU</a></li>
          <li><a href="https://polytech.ac.fj/">Polytech</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container copyright text-center mt-4">
    <p>2025 © <span>Copyright</span> <strong class="px-1 sitename">Kalabu Primary School</strong> <span>All Rights Reserved</span></p>
    <div class="credits">
      Powered by <a href="https://faithtech.pythonanywhere.com/">Faith Technology</a>
    </div>
  </div>

</footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <style>
    .hover-shadow:hover {
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  transition: box-shadow 0.3s ease;
  }

  .facebook-blue {
    color: #1877F2;
  }

  </style>

</body>

</html>